export const USER_ACTIONS = {
    FETCH_USERS: 'FETCH_USERS', SAVE_USER: 'SAVE_USER', DELETE_USER: 'DELETE_USER',
    ADD_USER: 'ADD_USER', SELECT_USER: 'SELECT_USER', CLOSE_USER: 'CLOSE_USER'
}

export const STATUS_ACTIONS = {
    ADD_ERROR : 'ADD_ERROR',    
    ADD_ERROR_SUCCESS : 'ADD_ERROR_SUCCESS',
    ADD_INFO : 'ADD_INFO',    
    ADD_INFO_SUCCESS : 'ADD_INFO_SUCCESS',
    CLEAR_ALL : 'CLEAR_ALL'
}