export const USER_ACTIONS = {
    FETCH_USERS: 'FETCH_USERS', FETCH_USERS_SUCCEED: 'FETCH_USERS_SUCCEED', FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',
    ADD_USER: 'ADD_USER', SELECT_USER: 'SELECT_USER', CANCEL_USER: 'CANCEL_USER',
    SAVE_USER: 'SAVE_USER', SAVE_USER_SUCCEED: 'SAVE_USER_SUCCEED', SAVE_USER_FAILED: 'SAVE_USER_FAILED',
    DELETE_USER: 'DELETE_USER', DELETE_USER_SUCCEED: 'DELETE_USER_SUCCEED', DELETE_USER_FAILED: 'DELETE_USER_FAILED',
}