/*export const ITEM_ACTIONS = {
    FETCH_ITEMS: 'FETCH_ITEMS', SAVE_ITEM: 'SAVE_ITEM', DELETE_ITEM: 'DELETE_ITEM',
    ADD_ITEM: 'ADD_ITEM', CLOSE_ITEM: 'CLOSE_ITEM'
}*/

export const STATUS_ACTIONS = {
    ADD_ERROR : 'ADD_ERROR',    
    ADD_ERROR_SUCCESS : 'ADD_ERROR_SUCCESS',
    ADD_INFO : 'ADD_INFO',    
    ADD_INFO_SUCCESS : 'ADD_INFO_SUCCESS',
    CLEAR_ERRORS : 'CLEAR_ERRORS',
    CLEAR_INFOS:'CLEAR_INFOS'
}

export const LOGIN_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
}